# Generated by Django 2.2.6 on 2019-10-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date_due',
        ),
    ]
