# Generated by Django 2.2.6 on 2019-10-11 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20191011_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todolist',
            name='date_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
