# Generated by Django 2.2.6 on 2019-10-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20191011_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_due',
            field=models.CharField(max_length=25),
        ),
    ]
