# Generated by Django 2.2.6 on 2020-01-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20200113_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
